In [ ]:
import pandas as pd

In [ ]:
df=pd.read_csv('/content/order.csv')

Part 1 -Python Basics

Addition

In [4]:
a=20
b=10
c=a+b
print(c)

30

In [ ]:
subtraction

In [5]:
c = a - b
print(c)

10

multiplication

In [6]:
c = a * b
print(c)

200

In [8]:
c=a/b
print (c)

2.0

Even and odd

In [13]:
num = 10

if num % 2 == 0:
  print('even')
else:
    print('odd')

even

Positive and negative

In [14]:
num = -5

if num > 0:
    print("Positive")
elif num < 0:
   print("Negative")
else:
  print("Zero")

Negative

find large number

In [15]:
numbers = [25, 67, 12, 89, 34]

largest = max(numbers)

print("Largest number:", largest)

Largest number: 89

count

In [18]:
numbers = [25, 67, 12, 89, 34]

for i in numbers:
    print(i, numbers.count(i))

25 1
67 1
12 1
89 1
34 1

"python is easy and python is powerful"
Expected result should show the frequency of each word.

In [19]:
text = "python is easy and python is powerful"

words = text.split()

for word in words:
    print(word, words.count(word))

python 2
is 2
easy 1
and 1
python 2
is 2
powerful 1

Part 2 – Pandas Data Analysis

first 5 record

In [22]:
df.head(5)

,Order_ID,Order_Date,Customer_Name,City,Product,Category,Quantity,Unit_Price,Discount,Payment_Mode,Status
0,ORD1001,2025-01-10,Priya Patel,Chennai,Air Fryer,Appliances,1,5499,20,Cash,Completed
1,ORD1002,2025-01-17,Rohan Mehta,Jaipur,Denim Jacket,Clothing,4,2799,5,UPI,Completed
2,ORD1003,2025-01-23,Ananya Reddy,Hyderabad,Denim Jacket,Clothing,5,2799,20,Bank Transfer,Cancelled
3,ORD1004,2025-02-10,Divya Joshi,Kolkata,Study Desk,Furniture,1,8999,10,Bank Transfer,Cancelled
4,ORD1005,2025-02-14,Sneha Iyer,Chennai,Power Bank,Electronics,4,1299,5,Cash,Completed

last 5 record

In [23]:
df.tail(5)

,Order_ID,Order_Date,Customer_Name,City,Product,Category,Quantity,Unit_Price,Discount,Payment_Mode,Status
55,ORD1056,2025-12-16,Sanjay Rao,Kolkata,Microwave Oven,Appliances,1,9999,20,UPI,Pending
56,ORD1057,2025-12-16,Isha Kapoor,Kolkata,Smartphone,Electronics,2,18999,5,UPI,Completed
57,ORD1058,2025-12-17,Sneha Iyer,Kolkata,Running Shoes,Clothing,1,2999,5,UPI,Pending
58,ORD1059,2025-12-19,Priya Patel,Jaipur,Microwave Oven,Appliances,2,9999,5,Cash,Completed
59,ORD1060,2025-12-24,Manish Tiwari,Jaipur,Bluetooth Headphones,Electronics,4,2499,20,Card,Cancelled

total number of row

In [24]:
df.shape

(60, 11)

column name, data type of all column

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60 entries, 0 to 59
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order_ID       60 non-null     object
 1   Order_Date     60 non-null     object
 2   Customer_Name  60 non-null     object
 3   City           60 non-null     object
 4   Product        60 non-null     object
 5   Category       60 non-null     object
 6   Quantity       60 non-null     int64
 7   Unit_Price     60 non-null     int64
 8   Discount       60 non-null     int64
 9   Payment_Mode   60 non-null     object
 10  Status         60 non-null     object
dtypes: int64(3), object(8)
memory usage: 5.3+ KB

2. Data Cleaning

missing value

In [28]:
df.isnull().sum()

Order_ID         0
Order_Date       0
Customer_Name    0
City             0
Product          0
Category         0
Quantity         0
Unit_Price       0
Discount         0
Payment_Mode     0
Status           0
dtype: int64

check dublicate value

In [30]:
df.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30    False
31    False
32    False
33    False
34    False
35    False
36    False
37    False
38    False
39    False
40    False
41    False
42    False
43    False
44    False
45    False
46    False
47    False
48    False
49    False
50    False
51    False
52    False
53    False
54    False
55    False
56    False
57    False
58    False
59    False
dtype: bool

incorrect data type

In [31]:
df.dtypes

Order_ID         object
Order_Date       object
Customer_Name    object
City             object
Product          object
Category         object
Quantity          int64
Unit_Price        int64
Discount          int64
Payment_Mode     object
Status           object
dtype: object

create new columns

Gross amount column

In [33]:
df['Gross_Amount'] = df['Quantity'] * df['Unit_Price']

In [35]:
df.head()

,Order_ID,Order_Date,Customer_Name,City,Product,Category,Quantity,Unit_Price,Discount,Payment_Mode,Status,Gross_Amount
0,ORD1001,2025-01-10,Priya Patel,Chennai,Air Fryer,Appliances,1,5499,20,Cash,Completed,5499
1,ORD1002,2025-01-17,Rohan Mehta,Jaipur,Denim Jacket,Clothing,4,2799,5,UPI,Completed,11196
2,ORD1003,2025-01-23,Ananya Reddy,Hyderabad,Denim Jacket,Clothing,5,2799,20,Bank Transfer,Cancelled,13995
3,ORD1004,2025-02-10,Divya Joshi,Kolkata,Study Desk,Furniture,1,8999,10,Bank Transfer,Cancelled,8999
4,ORD1005,2025-02-14,Sneha Iyer,Chennai,Power Bank,Electronics,4,1299,5,Cash,Completed,5196

final amount column

In [36]:
df['final_amount'] = df['Gross_Amount'] - df['Discount']

In [38]:
df.head()

,Order_ID,Order_Date,Customer_Name,City,Product,Category,Quantity,Unit_Price,Discount,Payment_Mode,Status,Gross_Amount,final_amount
0,ORD1001,2025-01-10,Priya Patel,Chennai,Air Fryer,Appliances,1,5499,20,Cash,Completed,5499,5479
1,ORD1002,2025-01-17,Rohan Mehta,Jaipur,Denim Jacket,Clothing,4,2799,5,UPI,Completed,11196,11191
2,ORD1003,2025-01-23,Ananya Reddy,Hyderabad,Denim Jacket,Clothing,5,2799,20,Bank Transfer,Cancelled,13995,13975
3,ORD1004,2025-02-10,Divya Joshi,Kolkata,Study Desk,Furniture,1,8999,10,Bank Transfer,Cancelled,8999,8989
4,ORD1005,2025-02-14,Sneha Iyer,Chennai,Power Bank,Electronics,4,1299,5,Cash,Completed,5196,5191

Part 3 – Analysis

	What is the total sales amount?

In [39]:
total_sales = df['Gross_Amount'].sum()
print(total_sales)

695097

What is the average order value?

In [40]:
average_order_value=df['final_amount'].mean()
print(average_order_value)

11573.533333333333

Which customer has generated the highest sales?

In [43]:
highest_sales_customer = df.groupby('Customer_Name')['final_amount'].sum().idxmax()
print(highest_sales_customer)

Priya Patel

Which city has generated the highest sales?

In [44]:
city_sales = df.groupby('City')['Gross_Amount'].sum()
city_sales.idxmax()

'Hyderabad'

Which product has been sold in the highest quantity?

In [45]:
product_qty = df.groupby('Product')['Quantity'].sum()
product_qty.idxmax()

'Denim Jacket'

Which product generated the highest revenue?

In [47]:
highest_revenue_product = df.groupby('Product')['final_amount'].sum().idxmax()
print(highest_revenue_product)

Smartphone

7.Show total sales by city.
8	Show total sales by product category.
9	Show total sales by payment mode.

In [51]:
total_sales_by_city=df.groupby('City')['final_amount'].sum()
print(total_sales_by_city)

City
Ahmedabad     30156
Bengaluru     83757
Chennai       83802
Delhi         99702
Hyderabad    134581
Jaipur        88318
Kolkata       95879
Lucknow       26051
Mumbai        15554
Pune          36612
Name: final_amount, dtype: int64

In [54]:
total_sales_by_product_category=df.groupby('Category')['final_amount'].sum()
print(total_sales_by_product_category)

Category
Appliances     146918
Clothing       100618
Electronics    289090
Furniture      147852
Stationery       9934
Name: final_amount, dtype: int64

In [55]:
total_sales_by_payment_mode=df.groupby('Payment_Mode')['final_amount'].sum()
print(total_sales_by_payment_mode)

Payment_Mode
Bank Transfer    197556
Card             117232
Cash             135511
UPI              244113
Name: final_amount, dtype: int64

10	Find the number of:
	•	Completed orders
  •	Pending orders
	•	Cancelled orders

In [57]:
completed = (df['Status'] == 'Completed').sum()
pending = (df['Status'] == 'Pending').sum()
cancelled = (df['Status'] == 'Cancelled').sum()

print("Completed:", completed)
print("Pending:", pending)
print("Cancelled:", cancelled)

Completed: 40
Pending: 11
Cancelled: 9

	11	Find the top 5 customers based on total purchase value.

In [59]:
df.groupby('Customer_Name')['Gross_Amount'].sum().sort_values(ascending=False).head(5)

Customer_Name
Priya Patel     84986
Rohan Mehta     80187
Ritu Agarwal    59081
Sanjay Rao      57894
Sneha Iyer      53684
Name: Gross_Amount, dtype: int64

Find the top 5 products based on revenue.

In [61]:
df.groupby('Product')['final_amount'].sum().sort_values(ascending=False).head(5)

Product
Smartphone        189915
Bookshelf          85930
Microwave Oven     79932
Denim Jacket       78277
Smartwatch         74945
Name: final_amount, dtype: int64

Find all orders where the final order amount is greater than ₹10,000.

In [62]:
df[df['Gross_Amount'] > 10000]

,Order_ID,Order_Date,Customer_Name,City,Product,Category,Quantity,Unit_Price,Discount,Payment_Mode,Status,Gross_Amount,final_amount
1,ORD1002,2025-01-17,Rohan Mehta,Jaipur,Denim Jacket,Clothing,4,2799,5,UPI,Completed,11196,11191
2,ORD1003,2025-01-23,Ananya Reddy,Hyderabad,Denim Jacket,Clothing,5,2799,20,Bank Transfer,Cancelled,13995,13975
5,ORD1006,2025-02-16,Ritu Agarwal,Chennai,Denim Jacket,Clothing,5,2799,20,UPI,Completed,13995,13975
8,ORD1009,2025-03-12,Deepak Chopra,Ahmedabad,Mixer Grinder,Appliances,5,3299,5,Bank Transfer,Pending,16495,16490
10,ORD1011,2025-03-13,Priya Patel,Delhi,Study Desk,Furniture,2,8999,0,Bank Transfer,Pending,17998,17998
11,ORD1012,2025-03-20,Neha Gupta,Chennai,Smartphone,Electronics,1,18999,5,Bank Transfer,Completed,18999,18994
15,ORD1016,2025-04-19,Priya Patel,Bengaluru,Mixer Grinder,Appliances,4,3299,15,Cash,Cancelled,13196,13181
16,ORD1017,2025-04-22,Sanjay Rao,Hyderabad,Smartphone,Electronics,2,18999,15,Bank Transfer,Completed,37998,37983
19,ORD1020,2025-05-06,Rohan Mehta,Bengaluru,Bookshelf,Furniture,5,4299,0,Cash,Completed,21495,21495
20,ORD1021,2025-05-21,Amit Kulkarni,Delhi,Smartphone,Electronics,1,18999,20,UPI,Completed,18999,18979
24,ORD1025,2025-06-07,Sneha Iyer,Delhi,Smartwatch,Electronics,5,4999,20,UPI,Completed,24995,24975
26,ORD1027,2025-06-22,Ritu Agarwal,Hyderabad,Office Chair,Furniture,2,6499,20,Cash,Completed,12998,12978
27,ORD1028,2025-06-26,Divya Joshi,Delhi,Smartwatch,Electronics,5,4999,5,Card,Completed,24995,24990
29,ORD1030,2025-07-14,Karan Malhotra,Hyderabad,Smartphone,Electronics,2,18999,20,Bank Transfer,Completed,37998,37978
34,ORD1035,2025-07-25,Priya Patel,Pune,Smartwatch,Electronics,3,4999,5,UPI,Completed,14997,14992
35,ORD1036,2025-08-05,Ritu Agarwal,Kolkata,Bookshelf,Furniture,3,4299,20,UPI,Cancelled,12897,12877
39,ORD1040,2025-09-13,Pooja Desai,Hyderabad,Bookshelf,Furniture,4,4299,5,UPI,Completed,17196,17191
41,ORD1042,2025-09-17,Pooja Desai,Jaipur,Microwave Oven,Appliances,2,9999,15,Card,Cancelled,19998,19983
44,ORD1045,2025-10-11,Sneha Iyer,Kolkata,Denim Jacket,Clothing,5,2799,20,UPI,Completed,13995,13975
45,ORD1046,2025-10-15,Aarav Sharma,Jaipur,Bookshelf,Furniture,4,4299,20,UPI,Completed,17196,17176
48,ORD1049,2025-11-05,Ritu Agarwal,Bengaluru,Bookshelf,Furniture,3,4299,5,Bank Transfer,Completed,12897,12892
49,ORD1050,2025-11-13,Ananya Reddy,Lucknow,Microwave Oven,Appliances,2,9999,20,Card,Completed,19998,19978
52,ORD1053,2025-11-25,Isha Kapoor,Bengaluru,Denim Jacket,Clothing,5,2799,0,Card,Completed,13995,13995
53,ORD1054,2025-12-05,Rohan Mehta,Chennai,Smartphone,Electronics,2,18999,10,UPI,Pending,37998,37988
56,ORD1057,2025-12-16,Isha Kapoor,Kolkata,Smartphone,Electronics,2,18999,5,UPI,Completed,37998,37993
58,ORD1059,2025-12-19,Priya Patel,Jaipur,Microwave Oven,Appliances,2,9999,5,Cash,Completed,19998,19993

Find all completed orders made using UPI.

In [65]:
mode_upi = df[(df['Status'] == 'Completed') & (df['Payment_Mode'] == 'UPI')]
mode_upi.head()

,Order_ID,Order_Date,Customer_Name,City,Product,Category,Quantity,Unit_Price,Discount,Payment_Mode,Status,Gross_Amount,final_amount
1,ORD1002,2025-01-17,Rohan Mehta,Jaipur,Denim Jacket,Clothing,4,2799,5,UPI,Completed,11196,11191
5,ORD1006,2025-02-16,Ritu Agarwal,Chennai,Denim Jacket,Clothing,5,2799,20,UPI,Completed,13995,13975
18,ORD1019,2025-04-28,Priya Patel,Lucknow,Mixer Grinder,Appliances,1,3299,15,UPI,Completed,3299,3284
20,ORD1021,2025-05-21,Amit Kulkarni,Delhi,Smartphone,Electronics,1,18999,20,UPI,Completed,18999,18979
24,ORD1025,2025-06-07,Sneha Iyer,Delhi,Smartwatch,Electronics,5,4999,20,UPI,Completed,24995,24975

Find the month with the highest sales.

In [67]:
df['Order_Date'] = pd.to_datetime(df['Order_Date'])
df['Month'] = df['Order_Date'].dt.month
monthly_sales = df.groupby('Month')['final_amount'].sum()
monthly_sales.sort_values(ascending=False).head(1)

Month
12    125516
Name: final_amount, dtype: int64

Part 4 – Pandas Operations

In [69]:
df['Payment_Mode'].value_counts() # value_counts

Payment_Mode
UPI              18
Cash             15
Bank Transfer    15
Card             12
Name: count, dtype: int64

In [71]:
df.loc[df['Gross_Amount'] > 10000].    #loc()

,Order_ID,Order_Date,Customer_Name,City,Product,Category,Quantity,Unit_Price,Discount,Payment_Mode,Status,Gross_Amount,final_amount,Month
1,ORD1002,2025-01-17,Rohan Mehta,Jaipur,Denim Jacket,Clothing,4,2799,5,UPI,Completed,11196,11191,1
2,ORD1003,2025-01-23,Ananya Reddy,Hyderabad,Denim Jacket,Clothing,5,2799,20,Bank Transfer,Cancelled,13995,13975,1
5,ORD1006,2025-02-16,Ritu Agarwal,Chennai,Denim Jacket,Clothing,5,2799,20,UPI,Completed,13995,13975,2
8,ORD1009,2025-03-12,Deepak Chopra,Ahmedabad,Mixer Grinder,Appliances,5,3299,5,Bank Transfer,Pending,16495,16490,3
10,ORD1011,2025-03-13,Priya Patel,Delhi,Study Desk,Furniture,2,8999,0,Bank Transfer,Pending,17998,17998,3
11,ORD1012,2025-03-20,Neha Gupta,Chennai,Smartphone,Electronics,1,18999,5,Bank Transfer,Completed,18999,18994,3
15,ORD1016,2025-04-19,Priya Patel,Bengaluru,Mixer Grinder,Appliances,4,3299,15,Cash,Cancelled,13196,13181,4
16,ORD1017,2025-04-22,Sanjay Rao,Hyderabad,Smartphone,Electronics,2,18999,15,Bank Transfer,Completed,37998,37983,4
19,ORD1020,2025-05-06,Rohan Mehta,Bengaluru,Bookshelf,Furniture,5,4299,0,Cash,Completed,21495,21495,5
20,ORD1021,2025-05-21,Amit Kulkarni,Delhi,Smartphone,Electronics,1,18999,20,UPI,Completed,18999,18979,5
24,ORD1025,2025-06-07,Sneha Iyer,Delhi,Smartwatch,Electronics,5,4999,20,UPI,Completed,24995,24975,6
26,ORD1027,2025-06-22,Ritu Agarwal,Hyderabad,Office Chair,Furniture,2,6499,20,Cash,Completed,12998,12978,6
27,ORD1028,2025-06-26,Divya Joshi,Delhi,Smartwatch,Electronics,5,4999,5,Card,Completed,24995,24990,6
29,ORD1030,2025-07-14,Karan Malhotra,Hyderabad,Smartphone,Electronics,2,18999,20,Bank Transfer,Completed,37998,37978,7
34,ORD1035,2025-07-25,Priya Patel,Pune,Smartwatch,Electronics,3,4999,5,UPI,Completed,14997,14992,7
35,ORD1036,2025-08-05,Ritu Agarwal,Kolkata,Bookshelf,Furniture,3,4299,20,UPI,Cancelled,12897,12877,8
39,ORD1040,2025-09-13,Pooja Desai,Hyderabad,Bookshelf,Furniture,4,4299,5,UPI,Completed,17196,17191,9
41,ORD1042,2025-09-17,Pooja Desai,Jaipur,Microwave Oven,Appliances,2,9999,15,Card,Cancelled,19998,19983,9
44,ORD1045,2025-10-11,Sneha Iyer,Kolkata,Denim Jacket,Clothing,5,2799,20,UPI,Completed,13995,13975,10
45,ORD1046,2025-10-15,Aarav Sharma,Jaipur,Bookshelf,Furniture,4,4299,20,UPI,Completed,17196,17176,10
48,ORD1049,2025-11-05,Ritu Agarwal,Bengaluru,Bookshelf,Furniture,3,4299,5,Bank Transfer,Completed,12897,12892,11
49,ORD1050,2025-11-13,Ananya Reddy,Lucknow,Microwave Oven,Appliances,2,9999,20,Card,Completed,19998,19978,11
52,ORD1053,2025-11-25,Isha Kapoor,Bengaluru,Denim Jacket,Clothing,5,2799,0,Card,Completed,13995,13995,11
53,ORD1054,2025-12-05,Rohan Mehta,Chennai,Smartphone,Electronics,2,18999,10,UPI,Pending,37998,37988,12
56,ORD1057,2025-12-16,Isha Kapoor,Kolkata,Smartphone,Electronics,2,18999,5,UPI,Completed,37998,37993,12
58,ORD1059,2025-12-19,Priya Patel,Jaipur,Microwave Oven,Appliances,2,9999,5,Cash,Completed,19998,19993,12

Part 5 – Bonus Task

new column net amount

In [75]:
df['net_amount'] = df['final_amount'] - df['Discount']
df.head()

,Order_ID,Order_Date,Customer_Name,City,Product,Category,Quantity,Unit_Price,Discount,Payment_Mode,Status,Gross_Amount,final_amount,Month,net_amount
0,ORD1001,2025-01-10,Priya Patel,Chennai,Air Fryer,Appliances,1,5499,20,Cash,Completed,5499,5479,1,5459
1,ORD1002,2025-01-17,Rohan Mehta,Jaipur,Denim Jacket,Clothing,4,2799,5,UPI,Completed,11196,11191,1,11186
2,ORD1003,2025-01-23,Ananya Reddy,Hyderabad,Denim Jacket,Clothing,5,2799,20,Bank Transfer,Cancelled,13995,13975,1,13955
3,ORD1004,2025-02-10,Divya Joshi,Kolkata,Study Desk,Furniture,1,8999,10,Bank Transfer,Cancelled,8999,8989,2,8979
4,ORD1005,2025-02-14,Sneha Iyer,Chennai,Power Bank,Electronics,4,1299,5,Cash,Completed,5196,5191,2,5186

In [77]:
def get_customer_report(customer_name):
    data = df[df["Customer_Name"] == customer_name]
    top_product = data.groupby("Product")["Quantity"].sum().idxmax()
    return {
        "Customer Name": customer_name,
        "Total Orders": len(data),
        "Total Quantity Purchased": int(data["Quantity"].sum()),
        "Total Purchase Amount": float(round(data["final_amount"].sum(), 2)),
        "Most Purchased Product": top_product,
    }

def get_city_report(city_name):
    data = df[df["City"] == city_name]
    top_product = data.groupby("Product")["Quantity"].sum().idxmax()
    return {
        "City": city_name,
        "Total Customers": data["Customer_Name"].nunique(),
        "Total Orders": len(data),
        "Total Quantity Sold": int(data["Quantity"].sum()),
        "Total Sales": float(round(data["final_amount"].sum(), 2)),
        "Top-Selling Product": top_product,
    }

In [79]:

print(get_customer_report('Priya Patel'))

{'Customer Name': 'Priya Patel', 'Total Orders': 7, 'Total Quantity Purchased': 14, 'Total Purchase Amount': 84926.0, 'Most Purchased Product': 'Mixer Grinder'}

In [80]:
print(get_city_report('Jaipur'))

{'City': 'Jaipur', 'Total Customers': 5, 'Total Orders': 6, 'Total Quantity Sold': 17, 'Total Sales': 88318.0, 'Top-Selling Product': 'Microwave Oven'}

TASK 3

In [82]:
pd.DataFrame([get_city_report(c) for c in df["City"].unique()]).to_csv("city_sales_report.csv", index=False)
pd.DataFrame([get_customer_report(c) for c in df["Customer_Name"].unique()]).to_csv("customer_sales_report.csv", index=False)
df.groupby("Product")[["Quantity", "final_amount"]].sum().to_csv("product_sales_report.csv")

In [84]:
!python --version

Python 3.13.15